### PR TITLE
remove colors.reset

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
I'm not exactly sure what colors.reset does, @dave-irvine, it seems to only make webpack go nuts. and doen't really do anything when in the shell.

**Comment by graingert** [comment]
otherwise, I'd like to do:

```js
var browserColors = {
    reset: function reset(v) {
        return v;
    }
};
var reset = process.browser ? browserColors : require('colors/safe');
var hiff = require('hiff');
```

to make webpack not go all silly silly

**Comment by dave-irvine** [comment]
Once upon a time it fixed an issue when mocha output results to the terminal using one of its reporters. Whether it is still broken or what reporter it was, I don't know.

**Comment by graingert** [comment]
🤷

**Comment by graingert** [comment]
@dave-irvine yeah so it looks fine without this, and works nice with webpack too.

**Pull request merged**
